### PR TITLE
Supported RTL texts

### PR DESCRIPTION
**Pull request by amereii**
Fixed https://github.com/jonataslaw/readmore/issues/11

### CODE REVIEW

**Comment by amereii** [comment]
@jonataslaw Can you please accept the PR?

**Comment by amereii** [comment]
@jonataslaw Can you please reply?

**Comment by jonataslaw** [comment]
Thanks for this PR!
LGTM, I will merge now

**Comment by amereii** [comment]
@jonataslaw Please release a version if possible

**Pull request merged**
