### PR TITLE
Update CHANGELOG to 3.0.0

### PR DESCRIPTION
**Pull request by maRci002**

### CODE REVIEW

**Comment by maRci002** [comment]
I was using the master branch, so I couldn't reopen PR #54.

**Comment by jonataslaw** [comment]
LGTM!

**Comment by maRci002** [comment]
That video still not showing up :(

**Comment by jonataslaw** [comment]
I'm going to convert it to gif.
I don't know why github doesn't accept video previews.

**Comment by maRci002** [comment]
The old GIF effect is awesome; I like it. The MP4 can be removed from the repository then.

**Pull request merged**
