### PR TITLE
Add custom styling and interactions for mentions, hashtags, and URLs

### LINKED ISSUE #42: [Feature Request] Add url detection and launch support
Love this package, and it works great! But would be awesome to have url detection and launch url support within the package. 

Edit: It appears launch url was added to the last merge, but it is not working on the main package.

### LINKED ISSUE #53: Enhanced styling and interaction support for mentions, hashtags, and URLs
#### Summary
I propose adding enhanced styling and interaction capabilities for specific text patterns within `ReadMoreText`, such as mentions, hashtags, and URLs. This feature would allow developers to customize the appearance of these elements and define custom actions when they are tapped, such as navigating to a user's profile when a mention is clicked.

#### Use Case
In many applications, text content includes special elements like mentions (`<@userId>`), hashtags (`#topic`), and URLs that users expect to interact with. For example, tapping on a mention might navigate to that user's profile page, and clicking a hashtag could show related content. Additionally, these elements often require distinct styling to stand out from the surrounding text, signaling to users that they are interactive.

#### Proposed Solution
Introduce a mechanism to define custom styles and tap actions for mentions, hashtags, and URLs within the `ReadMoreText` widget. This could be achieved through a list of `Annotation` objects (or a similar construct) where each annotation includes:
- A `RegExp` to match the specific pattern (mention, hashtag, URL).
- A `TextSpan Function` that allows developers to customize the style and define tap actions for matched text.

This approach would not only enhance the visual differentiation of these special text elements but also enable developers to implement interactive behaviors, enhancing user engagement with the content.

#### Handling Modified Data
An important aspect of this feature is handling cases where the displayed text is modified, such as converting a mention from `<@userId>` to a readable username (e.g., UserA). The solution should gracefully support such transformations, ensuring that the custom styles and interactions are preserved.

#### Impact
Implementing this feature would significantly increase the utility and flexibility of the `ReadMoreText` widget, making it a more powerful tool for developers creating content-rich applications.

### PR DESCRIPTION
**Pull request by maRci002**
#closes #53
#closes #42

https://github.com/jonataslaw/readmore/assets/8436039/f821568d-69ee-4ad3-a074-b5607b4ca463

https://github.com/jonataslaw/readmore/assets/8436039/3c7fc530-e550-4636-8de7-367cfe6ba9bd

#### Summary
This pull request introduces the ability to apply custom styling and define tap actions for special text elements such as mentions, hashtags, and URLs within the `ReadMoreText` widget. By leveraging a flexible annotation system, developers can now enhance the interactivity and visual appeal of text content, providing a richer user experience.

#### Features
- **Custom Styling and Tap Actions**: Developers can specify custom styles and tap actions for different types of text patterns. This is achieved through a new `annotations` parameter in `ReadMoreText`, which accepts a list of `Annotation` objects. Each `Annotation` object contains a regular expression to match specific text patterns and a builder function to customize the resulting `TextSpan`.
- **Enhanced User Interaction**: This feature enables interactive text elements within the `ReadMoreText` widget, allowing users to tap on mentions, hashtags, and URLs to perform actions like navigating to a user profile or displaying related content.
- **Flexible Text Transformations**: The system supports transforming matched text patterns into more readable forms (e.g., converting `<@userId>` to a user's name) while retaining custom styles and interactions.
- _Note_: this PR also includes the ability to control `isCollapsed` programmatically.

#### Implementation Details
- Introduced a new `Annotation` class to represent each customizable text pattern. This class includes a `RegExp` for pattern matching and a `TextSpan Function` for styling and interaction definition.
- Extended the `ReadMoreText` widget to accept an optional `annotations` parameter, enabling the application of the defined `Annotation` objects to the widget's text content.
- Implemented logic in `ReadMoreTextState` to apply the specified annotations to the text, transforming matches based on the provided `RegExp` and builder function within each `Annotation`.

#### Example Usage
```dart
ReadMoreText(
  'This is a sample text with a #hashtag, a mention <@123>, and a URL: https://example.com.',
  annotations: [
    Annotation(
      regExp: RegExp(r'<@(\d+)>'),
      spanBuilder: ({required String text, TextStyle? textStyle}) => TextSpan(
        text: 'User123',
        style: textStyle?.copyWith(color: Colors.blue),
        recognizer: TapGestureRecognizer()..onTap = () { /* Navigate to user profile */ },
      ),
    ),
    // Additional annotations for hashtags and URLs...
  ],
)
```

### CODE REVIEW

**Comment by jonataslaw** [comment]
It is awesome!!!
Thank you for your contribution!

**Comment by maRci002** [comment]
Should I update the changelog?

There are some breaking changes:
- Flutter 2.0 -> 3.0 (`textScaleFactor` has been replaced with `textScaler`)
- Removed: `callback` has been replaced by the `isCollapsed` controller
- Removed (but never released): `onLinkPressed` and `linkTextStyle`

**Comment by jonataslaw** [comment]
That would be amazing!
I will upload the new version to pub.dev today
Thanks for your effort

**Comment by maRci002** [comment]
I think there aren't any breaking changes:

- `textScaleFactor` can still be used but is marked with `@Deprecated`.
- `callback` can still be called but is also marked as deprecated.

Soon I will update PR

**Comment by jonataslaw** [comment]
LGTM

**Comment by maRci002** [comment]
I am going to push one more commit to update the README, Changelog, and the flagship video. The code is ok which was merged.

**Pull request merged**
