### PR TITLE
Url links are now clickable.

### PR DESCRIPTION
**Pull request by webdastur**

### CODE REVIEW

**Comment by lyorb** [comment]
Can you merge this pull request ? @jonataslaw

**Comment by jonataslaw** [comment]
Wow, congratulations, that looks great!

If we could pass an optional Regex parameter, it would be even better, because it would be possible to assign emails and numbers also clickable, but I'll accept this PR for now, because it looks great

**Comment by webdastur** [comment]
> 

Thank you!

**Comment by DennisAshford** [comment]
@webdastur would you be able to provide a quick example of how you made url's different colors and clickable? It doesn't seem to be working with the examples provided.

**Pull request merged**
