### PR TITLE
'nullOk'. nullOk: nullOk - flutter 2.0

### PR DESCRIPTION
**Pull request by epynic**
The nullOK is no longer available in APIs

### CODE REVIEW

**Comment by karabanovbs** [comment]
Why not `maybeLocaleOf `?
I think `maybeLocaleOf ` is equivalent of `localeOf` with `nullOk: true`.

**Comment by epynic** [comment]
@karabanovbs , yes your right thanks for the tip.

**Comment by fayeed** [comment]
@jonataslaw Any updates on this PR?

**Comment by ChangJoo-Park** [comment]
👍  Please support null safety

**Comment by jonataslaw** [comment]
Thanks for your contribution! LGTM

**Comment by matamune94** [comment]
I have error like top topic
```
G:/flutter-stable/flutter/.pub-cache/hosted/pub.dartlang.org/readmore-1.0.1/lib/readmore.dart:82:58: Error: No named parameter with the name 'nullOk'.
        widget.locale ?? Localizations.localeOf(context, nullOk: true);
```

My flutter version:
```
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (2 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

Any have idea ?

**Pull request merged**
